from app.models import PlatformMetrics, PlatformProfile, PlatformScores

PLATFORMS: list[PlatformProfile] = [
    PlatformProfile(
        id="siemens",
        name="Siemens SIMATIC",
        vendor="Siemens",
        summary="大型制造企业常用的端到端自动化生态。 / End-to-end automation ecosystem widely used in large manufacturing organizations.",
        best_for=["离散制造 / Discrete manufacturing", "标准化工厂 / Standardized plants", "长期生命周期 / Long lifecycle"],
        business_position="企业级标准平台 / Enterprise standard platform",
        licensing_model="TIA Portal 商业授权 / Commercial TIA Portal licensing",
        engineering_software="TIA Portal",
        ecosystem_risk="Medium",
        scores=PlatformScores(productivity=82, motion=78, safety=88, simulation=76, openness=66, scalability=91, talent=84, cost_efficiency=62),
        metrics=PlatformMetrics(tco_index=72, learning_curve=68, vendor_lock_in=74, migration_complexity=69),
    ),
    PlatformProfile(
        id="twincat",
        name="Beckhoff TwinCAT",
        vendor="Beckhoff",
        summary="面向 PC-based 控制、高性能运动控制与开放软件架构。 / PC-based control platform for high-performance motion and open software architecture.",
        best_for=["高速运动 / High-speed motion", "机器控制 / Machine control", "软件定义自动化 / Software-defined automation"],
        business_position="高性能工程平台 / High-performance engineering platform",
        licensing_model="运行时授权 / Runtime licensing",
        engineering_software="TwinCAT 3",
        ecosystem_risk="Medium",
        scores=PlatformScores(productivity=79, motion=95, safety=79, simulation=84, openness=90, scalability=86, talent=63, cost_efficiency=78),
        metrics=PlatformMetrics(tco_index=65, learning_curve=79, vendor_lock_in=55, migration_complexity=76),
    ),
    PlatformProfile(
        id="codesys",
        name="CODESYS",
        vendor="CODESYS Group / OEM ecosystem",
        summary="跨厂商 IEC 61131-3 平台，适合开放与多硬件策略。 / Cross-vendor IEC 61131-3 platform suited for open and multi-hardware strategies.",
        best_for=["OEM 控制器 / OEM controllers", "多供应商策略 / Multi-vendor strategy", "成本敏感项目 / Cost-sensitive projects"],
        business_position="开放生态选项 / Open ecosystem option",
        licensing_model="工具与运行时授权 / Tool and runtime licensing",
        engineering_software="CODESYS Development System",
        ecosystem_risk="Low",
        scores=PlatformScores(productivity=76, motion=70, safety=67, simulation=72, openness=92, scalability=74, talent=58, cost_efficiency=86),
        metrics=PlatformMetrics(tco_index=58, learning_curve=64, vendor_lock_in=38, migration_complexity=61),
    ),
    PlatformProfile(
        id="rockwell",
        name="Rockwell ControlLogix",
        vendor="Rockwell Automation",
        summary="北美市场强势的企业级控制平台，适合大型资产密集型工厂。 / Enterprise control platform with strong North American footprint for large asset-intensive plants.",
        best_for=["北美工厂 / North American plants", "过程与离散混合 / Hybrid process-discrete", "大型产线 / Large production lines"],
        business_position="资产密集型标准平台 / Asset-intensive standard platform",
        licensing_model="Studio 5000 商业授权 / Commercial Studio 5000 licensing",
        engineering_software="Studio 5000 Logix Designer",
        ecosystem_risk="High",
        scores=PlatformScores(productivity=77, motion=80, safety=86, simulation=70, openness=59, scalability=89, talent=78, cost_efficiency=55),
        metrics=PlatformMetrics(tco_index=81, learning_curve=72, vendor_lock_in=82, migration_complexity=78),
    ),
]
